[book]
authors = ["Ruixi-rebirth"]
language = "en"
multilingual = false
src = "src"
title = "Data-Structure"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/K-ON-Book/data-structure"
edit-url-template = "https://github.com/K-ON-Book/data-structure/edit/main/tutorial/src/{path}"

[output.html.playground]
editable = true
line-numbers = true
copyable = true
copy-js = true
runnable = true

[output.html.print]
enable = true
page-break = true 

[output.html.search]
enable=true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3

